# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:  
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run PyInstaller
      run: |
        # build executables
        python build_script.py
    - name: Install InnoSetup
      run: |
        curl -SL "http://files.jrsoftware.org/is/6/innosetup-6.0.5.exe" -o iscc-setup.exe
        .\iscc-setup.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES
    - name: Create Win Setup package
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.EXE" .\setup\setup.iss
        ls .\setup\
    - name: Make Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .\setup\output\dcug-setup.exe
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
